# Generated by Django 3.1 on 2021-03-04 20:06

from django.db import migrations, models
import django.db.models.deletion
import main.agmodels.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('lms_id', models.CharField(blank=True, max_length=20)),
                ('enabled', models.BooleanField(default=False)),
                ('error', models.BooleanField(default=False)),
                ('restricted_functions', models.CharField(blank=True, default='', max_length=200)),
                ('assignment_group_name', models.CharField(blank=True, max_length=100)),
                ('message', models.CharField(blank=True, max_length=100)),
                ('language', models.CharField(choices=[('python3', 'Python3'), ('cpp', 'C++'), ('c', 'C'), ('matlab', 'MATLAB')], max_length=20)),
                ('grading_strategy', models.CharField(default='grade_tasks_passing', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CodeBlock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_index', models.PositiveIntegerField()),
                ('end_index', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lms_id', models.CharField(max_length=20)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('enabled', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='FilenameMatch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename_match_function', models.CharField(choices=[('startswith', 'Starts with'), ('endswith', 'Ends with'), ('contains', 'Contains'), ('matches', 'Matches regex')], max_length=20)),
                ('filename_match_pattern', models.CharField(max_length=65)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lms_id', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lms_id', models.CharField(db_index=True, max_length=20)),
                ('submitted_at', models.DateTimeField()),
                ('attempt', models.IntegerField()),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.assignment')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.person')),
            ],
            options={
                'unique_together': {('lms_id', 'attempt')},
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correct_program', models.FileField(blank=True, upload_to=main.agmodels.models.task_resource_function)),
                ('name', models.CharField(max_length=20)),
                ('lms_question_id', models.CharField(blank=True, default='', max_length=20)),
                ('points_possible', models.FloatField(blank=True, default=0.0)),
                ('is_manual_grade', models.BooleanField(blank=True, default=False)),
                ('is_extra_credit', models.BooleanField(blank=True, default=False)),
                ('filename_match_function', models.CharField(choices=[('startswith', 'Starts with'), ('endswith', 'Ends with'), ('contains', 'Contains'), ('matches', 'Matches regex')], max_length=20)),
                ('filename_match_pattern', models.CharField(max_length=65)),
                ('lenient_whitespace', models.BooleanField(default=False)),
                ('ignore_whitespace', models.BooleanField(default=False)),
                ('ignore_case', models.BooleanField(default=False)),
                ('ignore_numerical', models.BooleanField(default=False)),
                ('ignore_alphabetical', models.BooleanField(default=False)),
                ('ignore_punctuation', models.BooleanField(default=False)),
                ('similarity_required', models.FloatField(default=1.0)),
                ('restricted_functions', models.CharField(blank=True, default='', max_length=200)),
                ('mandatory_functions', models.CharField(blank=True, default='', max_length=200)),
                ('preprocess_function', models.CharField(blank=True, default='', max_length=200)),
                ('postprocess_function', models.CharField(blank=True, default='', max_length=200)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.assignment')),
                ('driver_filename', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='driver_submission_file', to='main.filenamematch')),
            ],
        ),
        migrations.CreateModel(
            name='TestCase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restricted_functions', models.CharField(blank=True, default='', max_length=200)),
                ('stdin', models.CharField(blank=True, max_length=1000000)),
                ('stdout', models.CharField(blank=True, max_length=1000000)),
                ('hidden', models.BooleanField(default=False)),
                ('hint', models.CharField(blank=True, default='', max_length=200)),
                ('description', models.CharField(max_length=1000)),
                ('insert_code_before', models.CharField(blank=True, default='', max_length=2000)),
                ('rng_seed', models.PositiveIntegerField(blank=True, null=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.task')),
            ],
        ),
        migrations.CreateModel(
            name='TestcaseResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Passed', 'Passed'), ('Wrong Answer', 'Wrong Answer'), ('Rejected', 'Rejected'), ('Error', 'Error')], max_length=50)),
                ('program_input', models.CharField(max_length=10000)),
                ('program_output', models.CharField(max_length=1000000)),
                ('program_error', models.CharField(max_length=1000000)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.submission')),
                ('testcase', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.testcase')),
            ],
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(max_length=500, upload_to=main.agmodels.models.resource_filepath_function)),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task_resources', to='main.task')),
                ('testcase_as_input', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='input_resources', to='main.testcase')),
                ('testcase_as_output', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='output_resources', to='main.testcase')),
            ],
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=10000)),
                ('programming_language', models.CharField(max_length=100)),
                ('assignment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main.assignment')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.person')),
                ('submission', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main.submission')),
            ],
        ),
        migrations.CreateModel(
            name='PlagiarismCheck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('performed_at', models.DateTimeField(auto_now_add=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.assignment')),
            ],
        ),
        migrations.AddField(
            model_name='filenamematch',
            name='task_as_submission_filename',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='submission_filenames', to='main.task'),
        ),
        migrations.CreateModel(
            name='CodeSimilarity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('similar_code_1', models.CharField(max_length=50000)),
                ('percent_similar_1', models.DecimalField(decimal_places=2, max_digits=4)),
                ('similar_code_2', models.CharField(max_length=50000)),
                ('percent_similar_2', models.DecimalField(decimal_places=2, max_digits=4)),
                ('submission_1', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='submission_1', to='main.submission')),
                ('submission_2', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='submission_2', to='main.submission')),
            ],
        ),
        migrations.CreateModel(
            name='CodeBlockSimilarity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_block_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='code_block_1', to='main.codeblock')),
                ('code_block_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='code_block_2', to='main.codeblock')),
                ('plagiarism_check', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plagiarism_check', to='main.plagiarismcheck')),
            ],
        ),
        migrations.AddField(
            model_name='codeblock',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.program'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.course'),
        ),
    ]
