# Generated by Django 3.1 on 2021-02-19 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='mandatory_functions',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
