# Generated by Django 3.1 on 2021-03-13 03:38

from django.db import migrations, models
import django.db.models.deletion
import main.agmodels.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_task_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='has_updated_plagiarism_check',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='codeblocksimilarity',
            name='plagiarism_check',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='code_block_similarities', to='main.plagiarismcheck'),
        ),
        migrations.AlterField(
            model_name='program',
            name='assignment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='programs', to='main.assignment'),
        ),
        migrations.AlterField(
            model_name='program',
            name='submission',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='programs', to='main.submission'),
        ),
    ]
