# Generated by Django 3.1.1 on 2020-09-29 05:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('main', '0002_assignment_assignment_group_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='testcase',
            name='rng_seed',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
