# Generated by Django 3.1.2 on 2021-03-03 19:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_plagiarismcheck_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plagiarismcheck',
            name='updated_at',
        ),
    ]
