# Generated by Django 3.1.2 on 2020-11-05 01:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('main', '0004_auto_20201104_1247'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='assignment',
            name='error',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='course',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='submission',
            name='lms_id',
            field=models.CharField(db_index=True, max_length=20),
        ),
        migrations.RemoveField(
            model_name='testcase',
            name='input_resource_files',
        ),
        migrations.RemoveField(
            model_name='testcase',
            name='output_resource_files',
        ),
    ]
