# Generated by Django 3.1.2 on 2020-11-05 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20201105_0118'),
    ]

    operations = [
    ]
