# Generated by Django 3.1.2 on 2020-11-28 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20201105_0251'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='lms_question_id',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
