# Generated by Django 3.1.2 on 2020-11-28 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20201128_1603'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='points_possible',
            field=models.FloatField(blank=True, default=0.0),
        ),
    ]
