# Generated by Django 3.1.2 on 2020-11-30 17:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20201128_1604'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubmissionFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename_match_function', models.CharField(choices=[('startswith', 'Starts with'), ('endswith', 'Ends with'), ('contains', 'Contains'), ('matches', 'Matches regex')], max_length=20)),
                ('filename_match_pattern', models.CharField(max_length=65)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submission_files', to='main.task')),
            ],
        ),
        migrations.AddField(
            model_name='task',
            name='driver_submission_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='driver_submission_file', to='main.submissionfile'),
        ),
    ]
