# Generated by Django 3.1.2 on 2020-11-30 22:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20201130_2113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='driver_filename',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='driver_submission_file', to='main.filenamematch'),
        ),
    ]
