# Generated by Django 3.1.2 on 2020-12-14 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_auto_20201202_1627'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='is_manual_grade',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
