# Generated by Django 3.1.2 on 2021-02-03 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_auto_20201215_0235'),
    ]

    operations = [
        migrations.AddField(
            model_name='testcase',
            name='insert_code',
            field=models.CharField(blank=True, default='', max_length=2000),
        ),
    ]
