# Generated by Django 3.1.2 on 2021-02-07 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_auto_20210203_1737'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testcase',
            old_name='insert_code',
            new_name='insert_code_before',
        ),
    ]
