# Generated by Django 3.1.2 on 2021-02-20 03:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_auto_20210207_1725'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodeBlock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_start_index', models.PositiveIntegerField()),
                ('line_end_index', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=10000)),
                ('programming_language', models.CharField(max_length=100)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.submission')),
            ],
        ),
        migrations.CreateModel(
            name='CodeBlockSimilarity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_block_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='code_block_1', to='main.codeblock')),
                ('code_block_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='code_block_2', to='main.codeblock')),
            ],
        ),
        migrations.AddField(
            model_name='codeblock',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.program'),
        ),
    ]
