# Generated by Django 3.1.2 on 2021-02-19 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_auto_20210207_1725'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='language',
        ),
        migrations.AddField(
            model_name='assignment',
            name='language',
            field=models.CharField(choices=[('python3', 'Python3'), ('cpp', 'C++'), ('c', 'C'), ('matlab', 'MATLAB')], default='matlab', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='assignment',
            name='message',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
