# Generated by Django 3.1.1 on 2020-09-22 22:49

import django.db.models.deletion
from django.db import migrations, models

from main.lms.agmodels.models import task_filename_function, task_resource_function, testcase_input_resource_function, \
    testcase_output_resource_function


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('lms_id', models.CharField(blank=True, max_length=20)),
                ('enabled', models.BooleanField(default=True)),
                ('restricted_functions', models.CharField(blank=True, default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lms_id', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lms_id', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lms_id', models.CharField(max_length=20)),
                ('submitted_at', models.DateTimeField()),
                ('attempt', models.IntegerField()),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.assignment')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.person')),
            ],
            options={
                'unique_together': {('lms_id', 'attempt')},
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correct_program', models.FileField(blank=True, upload_to=task_resource_function)),
                ('task_resources', models.FileField(blank=True, upload_to=task_filename_function)),
                ('name', models.CharField(max_length=20)),
                ('language',
                 models.CharField(choices=[('python3', 'Python3'), ('cpp', 'C++'), ('c', 'C'), ('matlab', 'MATLAB')],
                                  max_length=20)),
                ('filename_match_function', models.CharField(
                    choices=[('startswith', 'Starts with'), ('endswith', 'Ends with'), ('contains', 'Contains'),
                             ('matches', 'Matches regex')], max_length=20)),
                ('filename_match_pattern', models.CharField(max_length=65)),
                ('lenient_whitespace', models.BooleanField(default=False)),
                ('ignore_whitespace', models.BooleanField(default=False)),
                ('ignore_case', models.BooleanField(default=False)),
                ('ignore_numerical', models.BooleanField(default=False)),
                ('ignore_alphabetical', models.BooleanField(default=False)),
                ('ignore_punctuation', models.BooleanField(default=False)),
                ('restricted_functions', models.CharField(blank=True, default='', max_length=200)),
                ('preprocess_function', models.CharField(blank=True, default='', max_length=200)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.assignment')),
            ],
        ),
        migrations.CreateModel(
            name='TestCase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restricted_functions', models.CharField(blank=True, default='', max_length=200)),
                ('input_resource_files',
                 models.FileField(blank=True, upload_to=testcase_input_resource_function)),
                ('stdin', models.CharField(blank=True, max_length=1000000)),
                ('output_resource_files',
                 models.FileField(blank=True, upload_to=testcase_output_resource_function)),
                ('stdout', models.CharField(blank=True, max_length=1000000)),
                ('hidden', models.BooleanField(default=False)),
                ('hint', models.CharField(blank=True, default='', max_length=200)),
                ('description', models.CharField(max_length=1000)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.task')),
            ],
        ),
        migrations.CreateModel(
            name='TestcaseResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(
                    choices=[('Passed', 'Passed'), ('Wrong Answer', 'Wrong Answer'), ('Rejected', 'Rejected'),
                             ('Error', 'Error')], max_length=50)),
                ('program_input', models.CharField(max_length=10000)),
                ('program_output', models.CharField(max_length=1000000)),
                ('program_error', models.CharField(max_length=1000000)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.submission')),
                ('testcase', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                               to='main.testcase')),
            ],
        ),
        migrations.CreateModel(
            name='CodeSimilarity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('similar_code_1', models.CharField(max_length=50000)),
                ('percent_similar_1', models.DecimalField(decimal_places=2, max_digits=4)),
                ('similar_code_2', models.CharField(max_length=50000)),
                ('percent_similar_2', models.DecimalField(decimal_places=2, max_digits=4)),
                ('submission_1',
                 models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='submission_1',
                                   to='main.submission')),
                ('submission_2',
                 models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='submission_2',
                                   to='main.submission')),
            ],
        ),
        migrations.AddField(
            model_name='assignment',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.course'),
        ),
    ]
