# Generated by Django 3.1.2 on 2020-11-28 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20201128_0815'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='points_possible',
        ),
    ]
