# Generated by Django 3.1.2 on 2020-12-01 10:19

from django.db import migrations, models
from main.lms.agmodels.models import resource_filepath_function


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20201130_2234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='file',
            field=models.FileField(max_length=500, upload_to=resource_filepath_function),
        ),
    ]
