# Generated by Django 3.1.2 on 2020-12-02 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_auto_20201201_1019'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='grading_strategy',
            field=models.CharField(default='grade_if_all_passing', max_length=100),
        ),
    ]
